### ISSUE TITLE
debian 7.8 > upload photo KO

### ISSUE THREAD

**Issue by christi9n** [cozy/cozy-photos-v2#115]
Hi,
Uploading photo on debian 7.8 with Iceweacel 36.0.4 doesn't work (drag and drop or classic upload) !?

**Comment by frankrousseau** [comment]
Thank you for reporting but we don't support Iceweacel. Did you try with Firefox or Chromium?

**Comment by christi9n** [comment]
Yes, I tried with both, it's KO.
It doesn't work.

**Comment by frankrousseau** [comment]
Are you sure that there is no file size limit in your Nginx configuration? Is there available disk space for your Cozy?

**Comment by christi9n** [comment]
Yes about the size, it's OK but sorry, what's Nginx and how can I check it ?

**Comment by frankrousseau** [comment]
Can you look for the following line in this file `/etc/nginx/conf.d/cozy.conf`?

```
 client_max_body_size 1024M;
```

**Comment by christi9n** [comment]
I don't have a "nginx" repertory in /etc !?
... but I've got a
/home/christian/fabfile.py file with that line
client_max_body_size 1024M;

**Comment by frankrousseau** [comment]
The fabfile is the file that will allow you to install Cozy on a remote server. Once the installation is processed, you're done with it. You must look for the nginx file on your remote server.

**Comment by christi9n** [comment]
I wanted first to install Cozy on my space on OVH wich wasn't possible.
So I asked Cozy.io a free instance of Coycloud ... I think you did it since the email was frank@cocycloud.cc .. I can't manage any remote server

**Comment by christi9n** [comment]
everything seems OK now with the new version of PHOTO 1.0.10 !

**Comment by frankrousseau** [comment]
Great news thx!
