### ISSUE TITLE
lg 3 android 5.0 non synchronization

### ISSUE THREAD

**Issue by christi9n** [cozy/cozy-photos-v2#116]
Hi,
No synchronization under android 5.0 with my LG3 ... the icon turns and turns again.
Some times when I choose "Synchronize" in the left menu, i've got the message "Alert: Database encountered an unknown error"

**Comment by frankrousseau** [comment]
Thank you @combaudon for reporting. We currently develop on Android 4.4. We add it to our current bug list.

**Comment by christi9n** [comment]
OK, if you want me to try on Android 5.0 .. feel free.

**Comment by poupotte** [comment]
@christi9n : this issue is still relevant ? I move it here : https://github.com/cozy/cozy-mobile/issues/153
