### ISSUE TITLE
upload still failing

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-photos-v2#118]
After updating my cozy, I can't upload picture to existing album. The upload starts, then the thumbnail turns to a grey box with a big red cross. Clicking the image opens a popup with "IMG_7379.JPG  : upload failled"

**Comment by frankrousseau** [comment]
@aenario Can you help on this one?

**Comment by dkm** [comment]
tried again, and it worked...

**Comment by dkm** [comment]
fails again...

**Comment by dkm** [comment]
new tries, some work, some don't,,,

**Comment by frankrousseau** [comment]
Something is definitely broken. Many people complain and I can't upload pictures anymore on my Cozy.

**Comment by dkm** [comment]
this morning, without even reloading the page (still in 'edit' mode) i was able to upload pictures that failed earlier... I tried to upload all at once (2 pictures..) or one at a time without any difference. It worked one at a time, but the same was failing yesterday so i'm not sure it's related.

**Comment by aenario** [comment]
@dkm , sorry for closing earlier. I thought it was fixed. @poupotte just made a fix in #120, could you check if it solves your problem ?

**Comment by dkm** [comment]
Will try that later today. Thanks !

**Comment by frankrousseau** [comment]
My Cozy Photos still crashes after a photo upload.

**Comment by frankrousseau** [comment]
Log:

```
[Tue, 31 Mar 2015 11:01:34 GMT] - POST /photos - 201 - 911.503 ms -  217
[Tue, 31 Mar 2015 11:01:35 GMT] - GET /photos/thumbs/f100ad9c759f8962298aa310d56fc580.jpg - 200 - 14.209 ms -  -
[Tue, 31 Mar 2015 11:01:36 GMT] - GET /photos/f100ad9c759f8962298aa310d56fc580.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:42 GMT] - GET /photos/57c5c795ee7e26eb7b9f005403158f78.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:42 GMT] - GET /photos/f791e138a4ea2ef42fae5e07f9c4f863.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:42 GMT] - GET /photos/f100ad9c759f8962298aa310d56fc580.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:44 GMT] - GET /photos/57c5c795ee7e26eb7b9f00540315aa1c.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:44 GMT] - GET /photos/f100ad9c759f8962298aa310d56fc580.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:44 GMT] - GET /photos/57c5c795ee7e26eb7b9f005403159b6e.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:45 GMT] - GET /photos/f100ad9c759f8962298aa310d56fc580.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:46 GMT] - GET /photos/f100ad9c759f8962298aa310d56fc580.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:48 GMT] - GET /photos/57c5c795ee7e26eb7b9f00540315aa1c.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:01:48 GMT] - GET /photos/57c5c795ee7e26eb7b9f005403158f78.jpg - - - - ms -  -
[Tue, 31 Mar 2015 11:02:20 GMT] - GET / - - - - ms -  -
```

**Comment by dkm** [comment]
Tried again last night and it worked fine...
But still some weird behavior: after having updated the app photo, when I open it again, I'm directly back to the 'edit' mode... I have this kind of behavior very often (not only with the photo app, but also with the main cozy page where I have something that kind of work, but not really: I need to login again to have a working UI...)

**Comment by frankrousseau** [comment]
@dkm Could you describe more precisely your bug, I mean can you give us a sequence of actions that leads to that state?

**Comment by frankrousseau** [comment]
On my side, the photo application looks to work.

**Comment by poupotte** [comment]
Upload on cozy-photos seems work now. @frankrousseau , @dkm , don't hesistate to reopen it if you have still issues.
