### ISSUE TITLE
App does not handle logout correctly

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-photos-v2#122]
It happens that I leave some session opened in different browsers. For some reason, some session may get invalid (not sure why), but the photo app does not see that and continues to mostly work. At least, it works enough to get user frustrated : you can see thumbnails, click on them, click on buttons in the iface... But no picture will be displayed (big grey cross instead).... Until you click on something that gets to back to the login screen : the problem is that the frontend does not see that its credentials have been revoked...

**Comment by frankrousseau** [comment]
Yes you're right, it can be really confusing.

**Comment by poupotte** [comment]
This issue is a duplicate of https://github.com/cozy/cozy-home/issues/452 .
