### ISSUE TITLE
Can't download one photo in shared album

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-photos-v2#124]
When I share an album, if I access it with the shared link, I can download album but I can't download only one picture. Indeed, button to download it in gallery isn't available.

**Comment by 0gust1** [comment]
+1 - https://forum.cozy.io/t/photos-appel-a-suggestions/1449/35

**Comment by 0gust1** [comment]
It's a bit strange, there is code to manage that, but it seems it's not working. 

I can't reproduce the comportement of production in my dev environnement. Maybe a problem with authorizations/flags (`app.mode`) ?

**Actual production (on cozycloud.cc)** : 
when logged : there is a button to download a given picture
when not logged (access with shared link) : no button

**Dev env**
when "logged" : no button to download image
when not logged : the sharing link doesn't work at all.

**Code** : 

https://github.com/cozy/cozy-photos/blob/master/client/app/views/galery.coffee#L92
condition : 
https://github.com/cozy/cozy-photos/blob/master/client/app/views/galery.coffee#L46

**Comment by frankrousseau** [comment]
Hello @0gust1, 

Do you use the `cozy-dev deploy` command to test the link?

**Comment by 0gust1** [comment]
Damned, I'm afraid that no.
Thanks for the reminder, I'll test asap.

**Comment by poupotte** [comment]
@clochix : It doesn't work for me :(.  haven't download button for only one picture in a shared album with new photo version (1.0.23)

**Comment by clochix** [comment]
Looks like a build issue, `app.js` has not been updated.
Ping @aenario

**Comment by poupotte** [comment]
Thanks @clochix , it works with 1.0.24 !
