### ISSUE TITLE
sp.coffee

### ISSUE THREAD

**Issue by hernando49** [cozy/cozy-photos-v2#130]
Add Spanish locale

**Comment by clochix** [comment]
We would be glad to have the Spanish locale, unfortunately none of us speaks Spanish. Would you mind help us ? All one need to do is copy `https://github.com/cozy/cozy-photos/tree/master/client/app/locales/en.coffee` to sp.coffee and translate the strings.

**Comment by frankrousseau** [comment]
I'm trying to configure Transifex. Can you see something here?

https://www.transifex.com/organization/cozy/dashboard/cozy-home

https://www.transifex.com/organization/cozy/dashboard/cozy-photos

**Comment by clochix** [comment]
Wrong links, try https://www.transifex.com/projects/p/cozy-home/ and https://www.transifex.com/projects/p/cozy-photos/

**Comment by hernando49** [comment]
bonjour

non je ne vois rien: page not found

j'essaie de me connecter dans le projet cozy de Transifex: réponse :
vous n'êtes pas membre du projet

hernando49
spanish es

amialement

hernando

**Comment by frankrousseau** [comment]
Je travaille encore dessus @hernando49 . Quand tout sera au propre je te préviendrai.

**Comment by hernando49** [comment]
merci

bien cordialement

**Comment by frankrousseau** [comment]
C'est bon tout est au propre, tu peux y aller @hernando49 ! Et un grand merci pour ta contribution !

**Comment by hernando49** [comment]
ok chers amis

je crois que je pourrai finir dans deux ou trois semaines. Il faut que
je passe les traductions faites au nouveau format qui est beaucoup plus
facile. J'ai essayé de charger mes fichiers txt format github a
Transifex mais c'est trop de galère au moins pour moi.

amicalement

hernando

**Comment by poupotte** [comment]
We have now Spanish local on cozy-photos. Thanks @hernando49 :)
