### ISSUE TITLE
Allow multiple selection in file pickup

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-photos-v2#131]
Hello,

When I choose photos to add in an album from file app. I would like to click on maj to select a range.

**Comment by 0gust1** [comment]
@m4dz  solved this on 18/03/2015, commit : dafe9bc7051f3934c145248381f510dd7620c7f0

It works on Chrome 47 and FF 43.0.1 (OSX)

**Comment by frankrousseau** [comment]
Thx @0gust1
