### ISSUE TITLE
Network errors on shared album public page

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-photos-v2#133]
When I access the public URL of a shared album, I get a lot of 404 in network console : 
- `https://xxx.cozycloud.cc/public/photos/clearance/contacts` : one time on page load;
- `https://xxx.cozycloud.cc/public/photos/socket.io/?EIO=3&transport=polling&t=1429553643445-0` : every few seconds

**Comment by poupotte** [comment]
This issue is now fixed. Thanks @clochix :+1:
