### ISSUE TITLE
Downloaded zip contains 21 Bytes files instead of photos

### ISSUE THREAD

**Issue by carrieje** [cozy/cozy-photos-v2#136]
I have assembled a gallery with 8 photos.
When I download it, the zip contains a file instead of each photo. The file is named after a hash and is 21Bytes.

```
e39ee91cb4a4611b79a8975b860b1074.jpg
...
```

**Comment by frankrousseau** [comment]
Thank you @carrieje for reporting. This problem was already reported. We are working on it.

**Comment by carrieje** [comment]
Sorry. I had made a search on the issues list though. :-)

**Comment by frankrousseau** [comment]
Users reported it was fixed.
