### ISSUE TITLE
Sharing pictures' email looks like SPAM

### ISSUE THREAD

**Issue by Thatoo** [cozy/cozy-photos-v2#141]
Hello,

The email I just received from my father who wanted to share some pictures with his cozy is not good.
The subject and the message are
"
Quelqu'un a partagé l'album "XXX" avec vous !
"
and the signature is 
"
Envoyé depuis le Cozy de Quelqu'un
"
Who is Quelqu'un?
and the email adresse it is send from is xxx-noreply@xxx-zzz.cozycloud.cc
Who this email adresse belongs to? I thought is was a spam (no, not me because I know what is cozy, but all the rest of my familly thought, at least I hope they thought because they should, it was a spam!).
Quelqu'un should be replaced by the name registered in cozy parameters and the sender email address should be also the one registered in cozy parameters. Don't you think?

My father registered name and email address in parameters so the problem is not coming from there. By the way, I wanted to change the name in cozy parameters to add the family name but when I click on change, the wheel turn, turn and turn for ever and the change is not saved.

**Comment by Thatoo** [comment]
After following the advice to update "photos", because I have been said that the message has been improved, it's not working at all anymore...
First, after clicking on the button to Share, when it comes to choose between "Partagé" and "Privé", there is nothing to select people inside "Privé" (What is that for? how to use the "privé" system?).
Then, if I click on "Partagé", I can select people to who I want to send a link (and I wanted to check how is the new message) but then, after clicking on "sauvegarder", I have an alerte saying " Erreur. Le message n'a pas pu être envoyé".
An other update is needed I guess :-)
Good luck,
![capture du 2015-06-08 18 55 32](https://cloud.githubusercontent.com/assets/464782/8044953/cf44b6d0-0e38-11e5-939a-31361612edf8.png)
![capture du 2015-06-08 18 56 02](https://cloud.githubusercontent.com/assets/464782/8044954/cf4d105a-0e38-11e5-95c1-f64b2e9ba7fa.png)

**Comment by Thatoo** [comment]
I uninstall and install again photos... I can't share my pictures anymore. Always the same error!

**Comment by frankrousseau** [comment]
If you update the platform and the photo application, it should work better.

**Comment by Thatoo** [comment]
Exact!
It works smotthly.
Thank you!
