### ISSUE TITLE
Missing search icon in the map

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-photos-v2#167]
When I open the map, the search icon (below the "+" and "-") on the top left is missing.
The CSS is looking for the icon at this URI : `/apps/photos/images/search-icon-mobile.png` but there is nothing there…

**Comment by clochix** [comment]
Thanks for reporting ☺
@miton18 would you mind having a look at this, maybe you forgot to commit an image?

**Comment by nicofrand** [comment]
The issue is still there ? @miton18

**Comment by miton18** [comment]
Sorry, I don't know I haven t commit this pic. I losed my setup(VB, vagrant, etc..) so if someone can put this https://github.com/stefanocudini/leaflet-search/blob/master/images/search-icon-mobile.png     in this folder https://github.com/cozy/cozy-photos/tree/master/client/app/assets/images

**Comment by clochix** [comment]
@nicofrand I already added the missing icon in 79de537, didn't I?

**Comment by miton18** [comment]
So, why we can't find this icon in https://github.com/cozy/cozy-photos/tree/master/build/client/public/images      ?

**Comment by aenario** [comment]
@clochix from what i see you did commit in your repo but forgot to make a PR :heart:

**Comment by clochix** [comment]
:'( Ok, my bad, thanks @nicofrand for fixing

**Comment by poupotte** [comment]
This issue should be fixed on new version : 1.0.22
