### ISSUE TITLE
Allow to display long descriptions

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-photos-v2#194]
As [requested in the forum](https://forum.cozy.io/t/photos-appel-a-suggestions/1449/36).

**Comment by poupotte** [comment]
I can resize description box only on edition mode. Thus, user who reads shared album can display long description :/

**Comment by clochix** [comment]
Same here, client files have not been updated in last build ☹

**Comment by poupotte** [comment]
Thanks @clochix , it's fixed now :+1:
