### ISSUE TITLE
Update max upload size

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-photos-v2#207]
Currently users can only upload [photos of less than 10 Mo](https://github.com/cozy/cozy-photos/blob/ad4db255761382cb16e098c08da05e7f5c0f3949/server/controllers/photo.coffee#L64). This limitation is annoying for some of them. We could either increase the limit or use streaming, like in files.

Files doesn't have such a limitation, so user can upload their photos to file and import them into Photos.

**Comment by frankrousseau** [comment]
@clochix yes, this limitation is sad. Can you fix this?

**Comment by clochix** [comment]
Ok. Updating to 50 Mo for now, “ought to be enough for anybody.”

**Comment by poupotte** [comment]
This issue should be now fixed in new version (v1.0.27)
