### ISSUE TITLE
Photos max size is too low

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-photos-v2#221]
I just noticed while using the app (for one of the first times) that there was a 10Mo size limit on the pictures supported by Photos.
I find this limit quite low regarding the fact that, with the resolutions and cameras we now have, it's quite easy to get over 10Mo for one picture. Which creates situations like, for example, me not being able to share all the photos I took from my trip to Paris earlier this week with my friends because some of these photos weight more than 10Mo. Of course I could compress them, of course, but that would downgrade the said pictures' quality.
For an app focused on managing and sharing pictures, it's quite a low limit we have here.

**Comment by clochix** [comment]
Related to #207 
Should have been fixed by 92eee32 (up to 50Mo) :-S

**Comment by babolivier** [comment]
Well I'm using v1.0.28 and I can attest that it hasn't been fixed yet :/

**Comment by clochix** [comment]
@frankrousseau discovered the limit was hard coded in another place and fixed this in  cc459d2 Unfortunately, the fix has not been published yet.

**Comment by frankrousseau** [comment]
ping @aenario could you publish a new version of Photos?

**Comment by poupotte** [comment]
In new version, max size is now 50Mo (https://github.com/cozy/cozy-photos/commit/cc459d2fe6bf242281957f597fa827dffe1096a7)
