### ISSUE TITLE
Problème d'orientation & ratio sur image en mode rafale

### ISSUE THREAD

**Issue by roumano** [cozy/cozy-photos-v2#235]
Dans la vue en mode gallerie des photos ( https://xxxxx-photos.mycozy.cloud/#/photos ) les photos prises en rafales sont pas bonnes : 
- l'orientation n'est pas bonne (il faut la tourné de 90°)
- le ratio hauteur/largeur n'est pas bonne

L'affichage en grand n'a pas le souci d'orientation
et les images prise sans rafale n'ont pas ces 2 soucis.

L'affichage de ces images n'a pas ces soucis sur mon PC ou sur mon smartphone ....

**Comment by GoOz** [comment]
Salut @roumano 

Quelques questions pour être certain de comprendre le problème.
(Pour visualiser je pars du principe que ce sont des photos en portrait mais l'exemple marcherait aussi pour du paysage).
Si les photos sont prises en mode portrait (hauteur > largeur), les vignettes sont affichées en mode paysage (largeur > hauteur) et pas exactement au bon ratio ? ou bien les photos prises en mode portrait, affichées en mode portrait mais l'image en elle-même n'est pas bien orientée et pour rentrer dans le format portrait elle est écrasée ?

**Comment by roumano** [comment]
Salut,

les images sources sont en modes portraits.
mais la miniature est en mode paysage et le ratio hauteur/largeur n'est pas le bon.

si j'affiche l'image en grand , le ratio devient bon mais toujours afficher en mode paysage au lieu de portrait.

Si je clique sur bouton droite/ afficher l'image (j'utilise firefox) : 
- l'url change pour avoir un .jpg a la fin,
- l'image passe en mode portrait.

Noter bien, que cela n'arrive pas sur toutes les photos mais que celle-prise en mode rafale, pourquoi, ca je sais pas.

J'ai telecharger 2 photos, une avec le souci l'autre non et lancer exif desus pour avoir les informations exif : 

* quand ca bug : 
```
--------------------+----------------------------------------------------------
Marqueur            |Valeur
--------------------+----------------------------------------------------------
Hauteur de l'image  |3968
Longeur de l'image  |2976
Bits des échantillon|8, 8, 8
Description de l'ima|bst
Constructeur        |HUAWEI
Modèle              |BLN-L21
Orientation         |Right-top
X-Resolution        |72
Y-Resolution        |72
Unité de la résoluti|pouces
Logiciel            |BLN-L21C432B369
Date et heure       |2018:01:26 07:54:08
Positionnement YCbCr|Centered
Hauteur de l'image  |512
Longeur de l'image  |384
Compression         |Compression JPEG
Orientation         |Right-top
X-Resolution        |72
Y-Resolution        |72
Unité de la résoluti|pouces
Temps d'exposition  |1/14 sec.
F-Number            |f/2,2
Exposure Program    |Programme normal
ISO Speed Ratings   |1000
Version d'exif      |Version d'exif 2.1
Date and Time (Origi|2018:01:26 07:54:08
Date and Time (Digit|2018:01:26 07:54:08
Components Configura|Y Cb Cr -
Shutter Speed       |29,90 EV (1/999963365 sec.)
Ouverture           |2,27 EV (f/2,2)
Luminosité          |0,00 EV (3,43 cd/m^2)
Exposure Bias       |0,00 EV
Mode de mesure      |Motif
Source lumineuse    |Lumière du jour
Flash               |Flash did not fire
Longueur focale     |3,8 mm
Note du créateur    |100 bytes undefined data
Sub-second Time     |025988
Sub-second Time (Ori|025988
Sub-second Time (Dig|025988
FlashPixVersion     |FlashPix Version 1.0
Espace des couleurs |sRGB
Pixel X Dimension   |3968
Pixel Y Dimension   |2976
Sensing Method      |One-chip color area sensor
Source du fichier   |DSC
Type de scène       |Directly photographed
Rendu personnalisé  |Processus personnel
Mode d'exposition   |Exposition automatique
Balance des blancs  |Balance des blancs automatique
Valeur du zoom numér|1,00
Focal Length in 35mm|26
Type de capture de l|Standard
Contrôle du gain    |Normal
Contraste           |Normal
Saturation          |Normal
Netteté             |Normal
Échelle de distance |Inconnu
Interoperability Ind|R98
Interoperability Ver|0100

```

* quand ca bug pas : 
```
--------------------+----------------------------------------------------------
Marqueur            |Valeur
--------------------+----------------------------------------------------------
Hauteur de l'image  |2976
Longeur de l'image  |3968
Bits des échantillon|8, 8, 8
Description de l'ima|dav
Constructeur        |HUAWEI
Modèle              |BLN-L21
Orientation         |Unknown value 0
X-Resolution        |72
Y-Resolution        |72
Unité de la résoluti|pouces
Logiciel            |BLN-L21C432B369
Date et heure       |2018:01:26 07:54:00
Positionnement YCbCr|Centered
Hauteur de l'image  |384
Longeur de l'image  |512
Compression         |Compression JPEG
Orientation         |Unknown value 0
X-Resolution        |72
Y-Resolution        |72
Unité de la résoluti|pouces
Temps d'exposition  |1/14 sec.
F-Number            |f/2,2
Exposure Program    |Programme normal
ISO Speed Ratings   |800
Version d'exif      |Version d'exif 2.1
Date and Time (Origi|2018:01:26 07:54:00
Date and Time (Digit|2018:01:26 07:54:00
Components Configura|Y Cb Cr -
Shutter Speed       |29,90 EV (1/999963365 sec.)
Ouverture           |2,27 EV (f/2,2)
Luminosité          |0,00 EV (3,43 cd/m^2)
Exposure Bias       |0,00 EV
Mode de mesure      |Motif
Source lumineuse    |Lumière du jour
Flash               |Flash did not fire
Longueur focale     |3,8 mm
Note du créateur    |100 bytes undefined data
Sub-second Time     |601050
Sub-second Time (Ori|601050
Sub-second Time (Dig|601050
FlashPixVersion     |FlashPix Version 1.0
Espace des couleurs |sRGB
Pixel X Dimension   |2976
Pixel Y Dimension   |3968
Sensing Method      |One-chip color area sensor
Source du fichier   |DSC
Type de scène       |Directly photographed
Rendu personnalisé  |Processus personnel
Mode d'exposition   |Exposition automatique
Balance des blancs  |Balance des blancs automatique
Valeur du zoom numér|1,00
Focal Length in 35mm|26
Type de capture de l|Standard
Contrôle du gain    |Normal
Contraste           |Normal
Saturation          |Normal
Netteté             |Normal
Échelle de distance |Inconnu
GPS Tag Version     |2.2.0.0
North or South Latit|N
Latitude            |45, 10, 14,067077
East or West Longitu|E
Longitude           | 5, 43, 59,259338
Altitude Reference  |Sea level
Altitude            |275,10
GPS Time (Atomic Clo|06:53:59,00
Name of GPS Processi|7 bytes undefined data
GPS Date            |2018:01:26
Interoperability Ind|R98
Interoperability Ver|0100

```

**Comment by GoOz** [comment]
Merci @roumano je pointerais donc en effet pour un problème avec la library de création d'image. 
ping @nono ça te parlera sûrement plus qu'à moi.

**Comment by jsilvestre** [comment]
Bonjour @roumano,

Merci beaucoup d'avoir pris le temps de nous rapporter ce bug.
On s'aperçoit qu'on a laissé ce dépôt ouvert alors qu'il ne correspond plus à l'app Photos actuelle (mais à celle de la précédente version de Cozy), donc nous allons clôre le ticket et archiver le dépôt. Je tenais tout de même à préciser que le problème ne passait pas à la trappe ! Est-il possible que tu me contactes sur joseph@cozycloud.cc afin que j'ai un moyen de te contacter pour davantages de précisions ? Merci !

Bonne journée,
Joseph.

**Comment by nono** [comment]
Bonjour @roumano, est-ce qu'il serait possible de m'envoyer une des images qui posent problème par mail à bruno [CHEZ] cozycloud [POINT] cc ?

**Comment by jsilvestre** [comment]
Bonjour @roumano,

On m'informe que le problème devrait être résolu. Peux-tu nous le confirmer s'il te plaît ? Il faudrait que tu transfert tes photos à nouveau.

Merci !

Joseph.

**Comment by jsilvestre** [comment]
Je ferme le ticket en l'absence de réponse. N'hésite pas à nous signaler si un problème survient à nouveau.

Bonne journée,
Joseph.
