### ISSUE TITLE
Break tags rendered as text in photo album titles

### ISSUE THREAD

**Issue by dullroar** [cozy/cozy-photos-v2#24]
If a newline is (accidentally) inserted in a photo album title, then when the title is displayed outside of edit mode, the "br" tag is rendered as text. Would be better if it were either rendered as a newline (assuming newlines in titles is something desired to be supported) or newlines were simply stripped/replaced with whitespace when saving from edit mode.

**Comment by poupotte** [comment]
Fix in https://github.com/mycozycloud/cozy-photos/commit/a3ab60026b28c0dae8e13945508d73efdd7a5288
