### ISSUE TITLE
Cannot delete photo album

### ISSUE THREAD

**Issue by aknock** [cozy/cozy-photos-v2#30]
Hi !

I installed CozyCloud on my personnal server but I can't delete any Photo Album.

I'm just here to report the issue.

I am very surprised of CozyCloud concept and I really love it !
Thank's guys !

**Comment by aenario** [comment]
Hi, 

I am not able to reproduce this bug.

Could you open your browser's console and see if there is any useful message there when you try to delete an album ? 

You can also try to stop and start the app and if it doesn't work to uninstall / reinstall it.

**Comment by aknock** [comment]
Okay, this morning I try and everything's good.

Sorry to bother you.
Antoine

**Comment by aenario** [comment]
No problems, let us know if you find any other bug :)

**Comment by aknock** [comment]
For sure :-)

PS : You are french guys no ? Can I report bugs in French or you prefer English (for language convention) ?

**Comment by aenario** [comment]
Oui oui, on est français. N'hésites pas  à ouvrir des issues en français, mets peut-être juste un petit tag [fr] dans le titre histoire de rassurer nos contributeurs étrangers :)

**Comment by aknock** [comment]
Ok ! J'ai hésité au début comme le projet a une vocation internationale.
Mais comme mon anglais n'est pas .. merveilleux, c'est pas toujours évident de s'expliquer.

Mais c'est noté ! Merci des réponses rapides en tout cas.
