### ISSUE TITLE
Photo-next animation starts before changing the photo

### ISSUE THREAD

**Issue by mihneadb** [cozy/cozy-photos-v2#35]
https://cloudup.com/cajZ6DEqfzy

**Comment by frankrousseau** [comment]
Thank you for reporting! That's definitely an issue.

**Comment by mihneadb** [comment]
I'm guessing this would be fixed (for free) by #34?

On Mon, Mar 10, 2014 at 5:26 PM, Frank Rousseau notifications@github.comwrote:

> Thank you for reporting! That's definitely an issue.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mycozycloud/cozy-photos/issues/35#issuecomment-37202178
> .

## 

Mihnea Dobrescu-Balaur

**Comment by frankrousseau** [comment]
Yep, maybe that an update could fix it too.

**Comment by mihneadb** [comment]
The demo [here](http://dropthebit.com/demos/photobox) does not have the bug, so .. yes. :)
