### ISSUE TITLE
Error when uploading several pictures at once

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-photos-v2#44]
I've dragged & dropped several picture right after album creation.
All thumbnails were displayed correctly and the "progress bar" (thumbnail being covered by blue) were working correctly. But all images reaching 100% have their blue box replaced by a grey one with "error" inside.

Going back showed an empty list of albums (I have at least 3)... Doing a forced refresh triggered a "internal server error"

Start/Stopping and doing a forced-refresh (a simple refresh wouldn't work) seems to bring the app again. The new album is here, but with only 5 pictures (at least ~10 were marked as 'error' and twice as much were scheduled for uploading...)

**Comment by dkm** [comment]
After giving it a new try, same erroneous behavior... This time, thumbnails are greyed with the picture name inside, when clicking it, a popup displays "upload failled". Refreshing the app gives an internal server error :(

**Comment by frankrousseau** [comment]
Hello Marc,

Thank you for reporting. We'll take a look at this problem. We have same kind of problems with file upload in Cozy Files. It looks related, we are putting our efforts on it.

**Comment by dkm** [comment]
Update on this issue.

This morning I've tried to upload several picture by drag & drop each picture, one by one. For the first ~15/20 pictures, it looked like it was working correctly. Then, drag & drop was not doing anything new on the page. After a going back to home and then back to photo app, the page was empty (like there was no album at all). After a stop/start of the photo app AND a forced brower refresh, I can see the album has been created, but is empty.

**Comment by dkm** [comment]
Ping. I decided to give it a new try :)
I've upgraded the photo app, then went to uploading few files (~10 jpeg, <2Mb each). The upload looked fine (still a bit strange with this blue filling). Then all the thumbnails turn grey (after being full blue). I guessed that it was finished and ok. Clicking on any picture opens a popup "my_file.jpg " upload failled" (I guess you could remove 1 l in failed ;)). Clicking back then shows an empty album. Refreshing brings a nice "It seems something went wrong". Restarting the app does not help for the content: the app is working, but album is empty.

**Comment by jsilvestre** [comment]
Could you please try with the latest version and tell us if it's still not working?

Thank you very much, you're almost our only source of reliable feedback for this app, this is very valuable!

**Comment by frankrousseau** [comment]
That one look solved and we have no news from @dkm about that issue. So, let's close it!

**Comment by dkm** [comment]
Sorry, I've been a bit busy lately. I'll try a have a look at my opened issues and check they are still valid and close them when applicable.

**Comment by frankrousseau** [comment]
No problem @dkm!
