### ISSUE TITLE
Can't reinstall app

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-photos-v2#45]
As I could not really use the app photo, I tried to remove + reinstall it, as it kind of fixed the files app...
It seems that it was not a good idea, as after the installation, when I try to open the app, I get the following in a popup. In the manage app, I can see it's "broken". Reinstalling it does not really work, as it's been nearly 10min that the app is "installing"...

This app is broken. Try install again. Error was : NPM Install failed :

  npm WARN package.json cozy-photos@1.0.2 No repository field.
  npm http GET https://npm-registry.cozycloud.cc:5448/async/0.9.0
  npm http GET https://npm-registry.cozycloud.cc:5448/zip-stream/0.3.7
  npm http GET https://npm-registry.cozycloud.cc:5448/jade/1.3.1
  npm http GET https://npm-registry.cozycloud.cc:5448/qs/0.6.6
  npm http GET https://npm-registry.cozycloud.cc:5448/node-polyglot/0.4.0
  npm http GET https://npm-registry.cozycloud.cc:5448/multiparty/3.2.9
  npm http GET https://npm-registry.cozycloud.cc:5448/cozy-clearance/0.1.11
  npm http GET https://npm-registry.cozycloud.cc:5448/imagemagick/0.1.3
  npm http GET https://npm-registry.cozycloud.cc:5448/printit/0.1.3
  npm http GET https://npm-registry.cozycloud.cc:5448/americano-cozy/0.2.7
  npm http GET https://npm-registry.cozycloud.cc:5448/americano/0.3.10
  npm http GET https://npm-registry.cozycloud.cc:5448/socket.io/1.0.6
  npm http 200 https://npm-registry.cozycloud.cc:5448/jade/1.3.1
  npm http GET https://npm-registry.cozycloud.cc:5448/jade/-/jade-1.3.1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/async/0.9.0
  npm http GET https://npm-registry.cozycloud.cc:5448/async/-/async-0.9.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/zip-stream/0.3.7
  npm http GET https://npm-registry.cozycloud.cc:5448/zip-stream/-/zip-stream-0.3.7.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/qs/0.6.6
  npm http GET https://npm-registry.cozycloud.cc:5448/qs/-/qs-0.6.6.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/node-polyglot/0.4.0
  npm http GET https://npm-registry.cozycloud.cc:5448/node-polyglot/-/node-polyglot-0.4.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/multiparty/3.2.9
  npm http GET https://npm-registry.cozycloud.cc:5448/multiparty/-/multiparty-3.2.9.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/imagemagick/0.1.3
  npm http GET https://npm-registry.cozycloud.cc:5448/imagemagick/-/imagemagick-0.1.3.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/cozy-clearance/0.1.11
  npm http GET https://npm-registry.cozycloud.cc:5448/cozy-clearance/-/cozy-clearance-0.1.11.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/printit/0.1.3
  npm http GET https://npm-registry.cozycloud.cc:5448/printit/-/printit-0.1.3.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/americano-cozy/0.2.7
  npm http GET https://npm-registry.cozycloud.cc:5448/americano-cozy/-/americano-cozy-0.2.7.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/jade/-/jade-1.3.1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/socket.io/1.0.6
  npm http 200 https://npm-registry.cozycloud.cc:5448/async/-/async-0.9.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/zip-stream/-/zip-stream-0.3.7.tgz
  npm http GET https://npm-registry.cozycloud.cc:5448/socket.io/-/socket.io-1.0.6.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/americano/0.3.10
  npm http GET https://npm-registry.cozycloud.cc:5448/americano/-/americano-0.3.10.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/node-polyglot/-/node-polyglot-0.4.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/multiparty/-/multiparty-3.2.9.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/imagemagick/-/imagemagick-0.1.3.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/cozy-clearance/-/cozy-clearance-0.1.11.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/qs/-/qs-0.6.6.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/americano-cozy/-/americano-cozy-0.2.7.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/printit/-/printit-0.1.3.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/socket.io/-/socket.io-1.0.6.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/americano/-/americano-0.3.10.tgz
  npm http GET https://npm-registry.cozycloud.cc:5448/jugglingdb/0.2.14
  npm http GET https://npm-registry.cozycloud.cc:5448/jugglingdb-cozy-adapter/0.4.11
  npm http GET https://npm-registry.cozycloud.cc:5448/buffer-crc32
  npm http GET https://npm-registry.cozycloud.cc:5448/crc32-stream
  npm http GET https://npm-registry.cozycloud.cc:5448/deflate-crc32-stream
  npm http GET https://npm-registry.cozycloud.cc:5448/debug
  npm http GET https://npm-registry.cozycloud.cc:5448/lodash
  npm http GET https://npm-registry.cozycloud.cc:5448/readable-stream
  npm http GET https://npm-registry.cozycloud.cc:5448/readable-stream
  npm http GET https://npm-registry.cozycloud.cc:5448/stream-counter
  npm http GET https://npm-registry.cozycloud.cc:5448/mkdirp/0.5.0
  npm http GET https://npm-registry.cozycloud.cc:5448/express/4.4.0
  npm http GET https://npm-registry.cozycloud.cc:5448/commander/2.2.0
  npm http GET https://npm-registry.cozycloud.cc:5448/body-parser/1.3.0
  npm http GET https://npm-registry.cozycloud.cc:5448/method-override/2.0.0
  npm http GET https://npm-registry.cozycloud.cc:5448/errorhandler/1.0.1
  npm http GET https://npm-registry.cozycloud.cc:5448/morgan/1.1.1
  npm http GET https://npm-registry.cozycloud.cc:5448/engine.io/1.3.1
  npm http GET https://npm-registry.cozycloud.cc:5448/socket.io-parser/2.2.0
  npm http GET https://npm-registry.cozycloud.cc:5448/socket.io-client/1.0.6
  npm http GET https://npm-registry.cozycloud.cc:5448/socket.io-adapter/0.2.0
  npm http GET https://npm-registry.cozycloud.cc:5448/has-binary-data/0.1.1
  npm http GET https://npm-registry.cozycloud.cc:5448/debug/0.7.4
  npm http GET https://npm-registry.cozycloud.cc:5448/async/0.2.10
  npm http GET https://npm-registry.cozycloud.cc:5448/commander/2.1.0
  npm http GET https://npm-registry.cozycloud.cc:5448/mkdirp
  npm http GET https://npm-registry.cozycloud.cc:5448/transformers/2.1.0
  npm http GET https://npm-registry.cozycloud.cc:5448/character-parser/1.2.0
  npm http GET https://npm-registry.cozycloud.cc:5448/monocle/1.1.51
  npm http GET https://npm-registry.cozycloud.cc:5448/with
  npm http GET https://npm-registry.cozycloud.cc:5448/constantinople
  npm http 200 https://npm-registry.cozycloud.cc:5448/jugglingdb-cozy-adapter/0.4.11
  npm http GET https://npm-registry.cozycloud.cc:5448/jugglingdb-cozy-adapter/-/jugglingdb
-cozy-adapter-0.4.11.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/jugglingdb/0.2.14
  npm http GET https://npm-registry.cozycloud.cc:5448/jugglingdb/-/jugglingdb-0.2.14.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/buffer-crc32
  npm http GET https://npm-registry.cozycloud.cc:5448/buffer-crc32/-/buffer-crc32-0.2.3.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/crc32-stream
  npm http GET https://npm-registry.cozycloud.cc:5448/crc32-stream/-/crc32-stream-0.2.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/deflate-crc32-stream
  npm http GET https://npm-registry.cozycloud.cc:5448/deflate-crc32-stream/-/deflate-crc32-stream-  0.1.1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/debug
  npm http GET https://npm-registry.cozycloud.cc:5448/debug/-/debug-1.0.4.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/readable-stream
  npm http GET https://npm-registry.cozycloud.cc:5448/readable-stream/-/readable-stream-  1.0.27-1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/lodash
  npm http GET https://npm-registry.cozycloud.cc:5448/lodash/-/lodash-2.4.1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/readable-stream
  npm http GET https://npm-registry.cozycloud.cc:5448/readable-stream/-/readable-stream-  1.1.13-1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/stream-counter
  npm http GET https://npm-registry.cozycloud.cc:5448/stream-counter/-/stream-counter-0.2.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/mkdirp/0.5.0
  npm http GET https://npm-registry.cozycloud.cc:5448/mkdirp/-/mkdirp-0.5.0.tgz
  npm http GET https://npm-registry.cozycloud.cc:5448/mkdirp/-/mkdirp-0.5.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/commander/2.2.0
  npm http GET https://npm-registry.cozycloud.cc:5448/commander/-/commander-2.2.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/express/4.4.0
  npm http GET https://npm-registry.cozycloud.cc:5448/express/-/express-4.4.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/body-parser/1.3.0
  npm http GET https://npm-registry.cozycloud.cc:5448/body-parser/-/body-parser-1.3.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/errorhandler/1.0.1
  npm http GET https://npm-registry.cozycloud.cc:5448/errorhandler/-/errorhandler-1.0.1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/morgan/1.1.1
  npm http GET https://npm-registry.cozycloud.cc:5448/morgan/-/morgan-1.1.1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/method-override/2.0.0
  npm http GET https://npm-registry.cozycloud.cc:5448/method-override/-/method-override-2.0.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/engine.io/1.3.1
  npm http GET https://npm-registry.cozycloud.cc:5448/engine.io/-/engine.io-1.3.1.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/socket.io-parser/2.2.0
  npm http GET https://npm-registry.cozycloud.cc:5448/socket.io-parser/-/socket.io-parser-2.2.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/socket.io-adapter/0.2.0
  npm http GET https://npm-registry.cozycloud.cc:5448/socket.io-adapter/-/socket.io-adapter-  0.2.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/debug/0.7.4
  npm http GET https://npm-registry.cozycloud.cc:5448/debug/-/debug-0.7.4.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/socket.io-client/1.0.6
  npm http GET https://npm-registry.cozycloud.cc:5448/socket.io-client/-/socket.io-client-1.0.6.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/async/0.2.10
  npm http GET https://npm-registry.cozycloud.cc:5448/async/-/async-0.2.10.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/mkdirp
  npm http GET https://npm-registry.cozycloud.cc:5448/mkdirp/-/mkdirp-0.3.5.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/commander/2.1.0
  npm http GET https://npm-registry.cozycloud.cc:5448/commander/-/commander-2.1.0.tgz
  npm http 200 https://npm-registry.cozycloud.cc:5448/transformers/2.1.0
  npm http GET https://npm-registry.cozycloud.cc:5448/transformers/-/transformers-2.1.0.tgz
  npm http

**Comment by dkm** [comment]
From a different computer (I don't know if something is displayed from the browser where I started the reinstallation), I cqn see in the notification that the install failed, and when I try to open the app anyway, I get the following in a popup : 

This app is broken. Try install again. Error was : ETIMEDOUT :
Error: ETIMEDOUT
    at null._onTimeout (/usr/local/cozy/apps/home/home/cozy-home/node_modules/cozy-clients/node_modules/request-json/node_modules/request/index.js:599:15)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by jsilvestre** [comment]
Hi @dkm 
Can you please try to reinstall the application? (when your Cozy problems will be solved, cf emails discussion) It should work now, let us know if anything isn't good.

**Comment by dkm** [comment]
app has been reinstalled, but I get the same sort of message when reinstalling 'Files'...

**Comment by jsilvestre** [comment]
I'm closing here too, don't hesitate to reopen the issues if something goes wrong again. Thanks!
