### ISSUE TITLE
cannot add photo at the album creation

### ISSUE THREAD

**Issue by lundyg** [cozy/cozy-photos-v2#51]
I create new album. I try to add a photo (d&d in the bottom left corner) ==> impossible

I go back home, reopen the album. now I can add photos

rdgs.
guillaume

**Comment by frankrousseau** [comment]
Thank you @lundyg  for reporting. A new version of photos is on the way. It should solve the problem.

**Comment by jsilvestre** [comment]
The new version has been merged, so it should be good. @lundyg, feel free to reopen the issue if it didn't solve your problem.
