### ISSUE TITLE
zip for album with many pictures

### ISSUE THREAD

**Issue by Piour** [cozy/cozy-photos-v2#6]
it seems i have problem to download an album with many pictures (zip file not readable)

**Comment by bibz** [comment]
Still an issue?
What is your platform?

I cannot reproduce the bug on my platform (GNU/Linux).

**Comment by Piour** [comment]
i'm using cozycloud on cozycloud.cc, i guess it's a debian vm. I tried again and it seems to work, i'll try again later with a bigger album. (i had more than 3Go of pictures, but i removed them since that time).

Sorry for the late answer and thanks for your interest.

**Comment by frankrousseau** [comment]
@Piour Do you still meet the problem?

**Comment by Piour** [comment]
I sorted and reduced photo sizes and photo count in all my photo sets so i dont have anymore any large enough set to use as an example.

It worked on a 160MB file.

I may give it a try if you need, but now.

**Comment by jsilvestre** [comment]
Closing for now, let us know if anything goes wrong again.
