### ISSUE TITLE
Fresh install of app does not work

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-photos-v2#64]
As I was not able to update the app (see https://github.com/cozy/cozy-files/issues/206 ), I've tried a remove/install cycle. Unfortunately, after reinstall, the app won't work and only shows

```
 It seems that something went wrong.

Don't worry, that's probably not so bad!
It should be a temporary issue, please try again in 5 minutes.
If nothing has changed despite that, try to restart your Cozy.

If the problem persists, feel free to contact the Cozy team:

    Ask for help on <a href="https://forum.cozy.io">our forum</a>error contact forum label
    Send an email at contact@cozycloud.cc
    Report the issue on IRC, #cozycloud on irc.freenode.net
```

It looks like the install did not succeed, as I can see it's broken status in the 'manage your app'. Surprisingly, the 'files' app has been stopped in the process (it was working before starting the install of photo app).

Reinstall went ok, but app crash the same. Its status is ok this time.

**Comment by jsilvestre** [comment]
Is is still crashed/crashing today?

**Comment by dkm** [comment]
This morning, app is in 'broken' status. It was not the case last night when I checked (the app looked fine (status ok) but crashed when I tried to open it).
I'll try a reinstall

**Comment by dkm** [comment]
Reinstall ok, status is ok, app still crash when opening.

**Comment by jsilvestre** [comment]
Thank you for keeping up so fast with my questions. I can't investigate properly your issue by myself, so I'm going to ask someone to check it and fix it.

**Comment by jsilvestre** [comment]
Thanks to @poupotte, we figured why it constantly crashed. We introduced a background patch that was to heavy performance-wise. We disabled it for now, and will work on it to make it smoother.

Anyway, you will still notice a slow down, due to a brand new feature: importing photos from the Files app when creating an album. We are currently working on it to make it explicit and your experience smoother.

For now, you can update the application, and it should work again!

**Comment by dkm** [comment]
Great! Thanks for the support :) Will try the files<=>photos bridge next time I need to broadcast pictures !

**Comment by jsilvestre** [comment]
I'm closing for now, feel free to reopen it if you have any trouble again!
