### ISSUE TITLE
Too many pictures from cozy files

### ISSUE THREAD

**Issue by Piour** [cozy/cozy-photos-v2#69]
I tried cozy-mobile and uploaded around 1500 pictures from my phone to my cozy. When I try to create albums in cozy-photos with the pictures of cozy-files, they take too long to load and cozy-photo eventually crash. I have to remove/install again cozy-photo to use it again.

Quick workaround : do not display thumbnails of all pictures. You show them by months, then just let me see the available months and let me click somewhere to display pictures of one month at a time.

**Comment by poupotte** [comment]
Hi @Piour,
thanks for your report. I'm working to add pagination in files modal. I'll inform you of my progress.

**Comment by frankrousseau** [comment]
The problem looks related to the thumbnail creation process.

What we should do: 
- Ensure that we do not spam the data system when building thumbnails.
- Create latest photo thumbnails first and build others silently.

**Comment by Piour** [comment]
I dont know what is going on now. All was working except this stuff with the photo orientation. You solved that with the imagemagick update, but now everytime i try to display the pictures from cozy-files to add them to my album, cozy crashes and i cant access my files from cozy-files ever.

**Comment by Piour** [comment]
Bug seems to be solved with the current version !
