### ISSUE TITLE
Album comment text Seems to not support NewLine character

### ISSUE THREAD

**Issue by LucsT** [cozy/cozy-photos-v2#7]
When I do an album with Firefox22.
I type a text like this : 
Salut.
Ca
 Va

I go back and then my text is
Salut.Ca Va

If I go back edit the comment I put:
Salut.
Ca
 Va
Bien

Get back and text is : 
Salut.Ca VaBien

Lucas

**Comment by aenario** [comment]
fixed in e568ebea933457e7bc63688fc9b62a2aec27b331
