### ISSUE TITLE
error when changing photo orientation

### ISSUE THREAD

**Issue by Piour** [cozy/cozy-photos-v2#70]
When i change a photo orientation, the photo become a blank square with "error" inside (when displayed, the thumbnail is ok, and when i download the photo i get it).

**Comment by frankrousseau** [comment]
I updated your Cozy with the latest Image Magick version. Could you try again?

**Comment by Piour** [comment]
Yes it works now, thanks !

**Comment by frankrousseau** [comment]
Great!
