### ISSUE TITLE
Importing images from cozyfiles is broken on photos 1.0.4

### ISSUE THREAD

**Issue by ghost** [cozy/cozy-photos-v2#78]
steps to reproduce:
1. Open one album
2. Choose _Edit_
3. Select _click here to pick from cozyfiles_
A modal window shows with no thumbnail images but broken image links instead, plus some bits of message (or is it code ?). see screenshot
![ajouterdepuisfiles](https://cloud.githubusercontent.com/assets/858630/5594804/4dcc583a-925d-11e4-8013-81406038ced9.png)
Additionaly, the French version shows an untranslated _cancel_ button.

**Comment by jsilvestre** [comment]
Hi @goofy-bz 

Could you please update your application? Just to be sure we are on the same version.
If you encounter this bug again after the update, could you please open the browser console and give me what it tells you?

Thanks!

**Comment by ghost** [comment]
I have repeatedly updated the app but it seems to be stuck on 1.0.4

after same test as above, I got
GET https://goofy.cozycloud.cc/apps/photos/files/ [HTTP/1.1 200 OK 69ms]
GET https://goofy.cozycloud.cc/apps/photos/files/thumbs/undefined.jpg [HTTP/1.1 404 Not Found 60ms]
as I am uncertain which dev tool may help you identify the glitch, here is a screenshot
(tell me if you need more/other stuff)

![capturedebug](https://cloud.githubusercontent.com/assets/858630/5597292/f738012a-929f-11e4-95a8-3adbff3780cc.png)

**Comment by jsilvestre** [comment]
Thank you very much, I will try to reproduce based on those new informations.
About version number, we don't bump them all the time, so sometimes there is something to update, but the version number doesn't change.

**Comment by ghost** [comment]
Hey it is working seamlessy now! Either you already fixed it or there was something wrong on my install: in the meanwhile I updated both cozy-files and the whole platform. Thx for your patience, whatever happened.
![muchbetterimport2](https://cloud.githubusercontent.com/assets/858630/5602860/171cf2f0-936a-11e4-8d88-f28d44965097.png)
