### ISSUE TITLE
Photo orientation

### ISSUE THREAD

**Issue by scesbron** [cozy/cozy-photos-v2#8]
Vertical photos (height bigger than width) are shown horizontally which is not the correct orientation for the photo.

**Comment by bibz** [comment]
+1
Even with the EXIF info saying that it should be "vertical".

**Comment by frankrousseau** [comment]
We are working on it, you can follow and participate to our trello board: https://trello.com/b/lKFyRnBR/cozy-photos

Thank you for the issue report!

**Comment by frankrousseau** [comment]
Bug fixed
