### ISSUE TITLE
Displaying number of photos per album: cases < 2 should be managed 

### ISSUE THREAD

**Issue by ghost** [cozy/cozy-photos-v2#80]
When there is only 1 or even 0 photo in an album, the interface shows "1 photos" and "0 photos".
Singular and zero cases should be managed with " 1 photo" an "no photo" 
I suppose the issue can be fixed in app/templates/album.jade around line 35 
![1photos](https://cloud.githubusercontent.com/assets/858630/5607630/ca12f956-9462-11e4-9a91-d359c610aff4.png)
![singulier_0photos](https://cloud.githubusercontent.com/assets/858630/5607631/dbbb4212-9462-11e4-8e26-978b523a598c.png)

**Comment by 0gust1** [comment]
Issue still present, see also #117

**Comment by poupotte** [comment]
Thanks @0gust1 , with version 1.0.20, it works well in french version :+1: . 
However, in english version, "1 picture" is well displayed but "0 pictures" is still in plural.

**Comment by 0gust1** [comment]
Did you change your navigator locale when testing ?
The reason could that the "pluralization engine" of polyglot.js here is initialized with the navigator locale (and not with the localization settings of Cozy's configuration). Imho, navigator locale should be ok for majority of user-cases, but it's suboptimal and debatable.

**Comment by 0gust1** [comment]
Ah, sorry @poupotte I misread your comment. In fact it's okay. In english "0" with a noun is plural. The pluralization engine of polyglot.js works well.

http://english.stackexchange.com/questions/13073/correct-plural-form-of-a-zero-quantified-noun
http://www.bbc.co.uk/worldservice/learningenglish/grammar/learnit/learnitv354.shtml

Pluralization can be pretty hairy (the worst is in russian, but it's handled by polyglot as well)

**Comment by poupotte** [comment]
Thanks @0gust1 :) !
So, I close this issue
