### ISSUE TITLE
import multiple photo with file picker broken

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-photos-v2#81]
When you edit an album, if you add photo by clicking on the button to open the file picker (note files from cozy-files), then if you choose 3 photo, then it will fail.
If you choose only one photo, it will work.

**Comment by frankrousseau** [comment]
@clochix Could you have a look at it tomorrow morning?

**Comment by clochix** [comment]
I'm unable to reproduce this issue, could you give me more informations ? (browser, OS, application version ?)

**Comment by frankrousseau** [comment]
Same here, I can't reproduce. Could you try again @Benibur?
