### ISSUE TITLE
drag'n drop of photo for upload is broken

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-photos-v2#82]
if you dragn' drop a file over an album in edit mode, it crashes.
it doesn't seem to be linked to a number of files droped, nor to the format (png, gif or non image files).
tested with ff 34.0 and chromium Version 39.0.2171.65

**Comment by clochix** [comment]
Works for me (and other people). @jsilvestre thinks it may be related to https://github.com/cozy/cozy-data-system/pull/115

**Comment by jsilvestre** [comment]
I corrected myself, not related to cozy/cozy-data-system#115, but I still think it's related to the DS itself.

**Comment by dkm** [comment]
Works correctly here (iceweasel 32 on Debian sid 64)

**Comment by frankrousseau** [comment]
Ok great!

**Comment by frankrousseau** [comment]
Thank you @dkm for the feedback.
