### ISSUE TITLE
Can't [re]install app

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-photos-v2#87]
I wanted to upload few pictures and as photo app was broken on login (red icon in the home screen, error on first try to run it), As my try to upgrade it failed, I tried to remove it (ok) and then install it (ok), but I can't run it " It seems that something went wrong. ..."

**Comment by frankrousseau** [comment]
I noticed the same problem. I can't install the application anymore. I'm still looking why.

**Comment by dkm** [comment]
Any news ? I was really looking forward to using cozy for sharing pictures during the next few months, but it still looks a bit unstable at the moment :'(

**Comment by dkm** [comment]
No news here, but I've been able to reinstall app and use it correctly. Thanks ! :)
