### ISSUE TITLE
rotating is not always persistant

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-photos-v2#97]
Sometimes rotating a picture when viewing it is persistent (rotation is preserved across different viewings), sometimes not. Can't figure why.

**Comment by dkm** [comment]
in fact, when rotating from private view' it does not work. But when using public link, rotation is correctly saved.

**Comment by dkm** [comment]
it works but only until you close the viewer...

**Comment by frankrousseau** [comment]
Ok, one more thing to fix! Thank you for reporting.

**Comment by dkm** [comment]
and now it works from private link...

**Comment by frankrousseau** [comment]
@dkm It should be fixed in the upcoming version (publication planned tomorrow).

**Comment by frankrousseau** [comment]
Hi @dkm,
Do you still meet issues about rotation? We published a new version last friday.

**Comment by dkm** [comment]
No issue again (yet). I was gladly surprised by the automatic rotation of pictures !

**Comment by frankrousseau** [comment]
Great news! Thank you for reporting and checking again.
